version: '3'

services:
  postman:
    build: .
    container_name: postman
    environment:
      API_TOKEN : 'production token'

  postman_stage:
    build: .
    container_name: postman_stage
    environment:
      API_TOKEN : 'stage api token'
      STAGE : 'on'

  redis:
    image: redis:7-alpine
    container_name: postman_redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data

  postgres:
    image: postgres:15-alpine
    container_name: postman_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345

    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - /data/postgres:/var/lib/postgresql/data
